## networking
networking.riftmanager.rats_announce0=RATS RATS RATS!
networking.riftmanager.rats_announce1=GET HIM! SWARM HIM!
networking.riftmanager.rats_announce2=*insert rat noises*


networking.gamemode.classic_name=Classic RTA
networking.gamemode.classic_rift_name=Rift RTA
networking.gamemode.bingo_name=Bingo