## networking
networking.riftmanager.rats_announce0=RATS RATS RATS!
networking.riftmanager.rats_announce1=GET HIM! SWARM HIM!
networking.riftmanager.rats_announce2=*insert rat noises*


networking.gamemode.classic_name=Classic RTA
networking.gamemode.classic_rift_name=Rift RTA
networking.gamemode.bingo_name=Bingo

networking.bingocondition.reach_floor=Get to floor %s
networking.bingocondition.random_potion=Drink a %s
networking.bingocondition.random_scroll=Read a %s
networking.bingocondition.cloth_upgrade=Upgrade cloth armor to +%s
networking.bingocondition.kill_piranha=Kill %s piranhas
networking.bingocondition.kill_trap=Kill %s enemies with traps
networking.bingocondition.kill_enemies=Kill %s enemies
networking.bingocondition.shopkeeper_fled=Scare a shop-keeper away
networking.bingocondition.chasms_fallen=Jump or fall down %s chasms
networking.bingocondition.craft_exotic_potion=Craft a %s
networking.bingocondition.craft_exotic_scroll=Craft a %s